### ISSUE TITLE
Permission issue when using android sdk 35

### ISSUE THREAD

**Issue by Shubhendra8449** [zoontek/react-native-permissions#960]
### Before submitting a new issue

- [x] I tested using the latest version of the library, as the bug might be already fixed.
- [x] I tested using a [supported version](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md) of react native.
- [x] I checked for possible duplicate issues, with possible answers.

### Bug summary

The error you're seeing during the React Native build process is caused by a Kotlin compilation error in the expo-modules-core module. Here's a breakdown of the key issues and how to fix them:

This means there's a null-safety issue in PermissionsService.kt, line 166. Kotlin is preventing access to a potentially null array.

"react-native-permissions": "^5.4.1",

### Library version

5.4.1

### Environment info

```shell
D:\LPA>npm run android

w: file:///D:/LPA/node_modules/react-native-screens/android/src/paper/java/com/swmansion/rnscreens/FabricEnabledViewGroup.kt:11:42 Parameter 'width' is 
never used
w: file:///D:/LPA/node_modules/react-native-screens/android/src/paper/java/com/swmansion/rnscreens/FabricEnabledViewGroup.kt:11:54 Parameter 'height' is never used
w: file:///D:/LPA/node_modules/react-native-screens/android/src/paper/java/com/swmansion/rnscreens/FabricEnabledViewGroup.kt:11:67 Parameter 'headerHeight' is never used

> Task :expo-modules-core:compileDebugKotlin FAILED
e: file:///D:/LPA/node_modules/expo-modules-core/android/src/main/java/expo/modules/adapters/react/permissions/PermissionsService.kt:166:36 Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type Array<(out) String!>?

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':expo-modules-core:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 1m 37s
399 actionable tasks: 205 executed, 171 from cache, 23 up-to-date
Error: D:\LPA\android\gradlew.bat app:assembleDebug -x lint -x test --configure-on-demand --build-cache -PreactNativeDevServerPort=8081 -PreactNativeArchitectures=x86_64,arm64-v8a exited with non-zero code: 1
```

### Steps to reproduce

1. …
2. …

### Reproducible sample code

```js
It is a compile time error
```

**Comment by Shubhendra8449** [comment]
The error you're seeing during the React Native build process is caused by a Kotlin compilation error in the expo-modules-core module. Here's a breakdown of the key issues and how to fix them:

**Comment by zoontek** [comment]
Not related to this library, but to https://docs.expo.dev/guides/permissions/

**Comment by Shubhendra8449** [comment]
Hi @zoontek,

I'm facing an issue after updating the target SDK version to 35. It was working fine with target SDK version 34.

Here’s my build.gradle configuration:

gradle
buildscript {
    ext {
        buildToolsVersion = findProperty('android.buildToolsVersion') ?: '35.0.0'
        minSdkVersion = Integer.parseInt(findProperty('android.minSdkVersion') ?: '23')
        compileSdkVersion = Integer.parseInt(findProperty('android.compileSdkVersion') ?: '35')
        targetSdkVersion = Integer.parseInt(findProperty('android.targetSdkVersion') ?: '35')
        kotlinVersion = findProperty('android.kotlinVersion') ?: '1.9.23'
        ndkVersion = "26.1.10909125"
    }
}
You can check this file:

node_modules/expo-modules-core/android/src/main/java/expo/modules/adapters/react/permissions/PermissionsService.kt

The issue occurs at line 166:

override fun isPermissionPresentInManifest(permission: String): Boolean {
    try {
        context.packageManager.getPackageInfo(context.packageName, PackageManager.GET_PERMISSIONS)?.run {
            return requestedPermissions?.contains(permission) == true
        }
        return false
    } catch (e: PackageManager.NameNotFoundException) {
        return false
    }
}

This is the corrected code compatible with Android SDK 35. Please review your implementation, as your current code might throw an error with SDK 35 if null safety is not properly handled.

Looking forward to your response. Let me know if any additional information is needed.

**Comment by zoontek** [comment]
**node_modules/expo-modules-core**/android/src/main/java/expo/modules/adapters/react/permissions/PermissionsService.kt

Does not starts with **node_modules/react-native-permissions**

**Comment by Shubhendra8449** [comment]
Can you clarify this for me? It's not understandable.

node_modules/expo-modules-core/android/src/main/java/expo/modules/adapters/react/permissions/PermissionsService.kt

Does not starts with node_modules/react-native-permissions

**Comment by zoontek** [comment]
@Shubhendra8449 `node_modules/expo-modules-core` != `node_modules/react-native-permissions`. This repository package is called `react-native-permissions`, the issue you describe doesn't come from it, but from `expo-modules-core`. You opened an issue on the wrong dependency repository.
