### ISSUE TITLE
iOS Build failed 

### ISSUE THREAD

**Issue by DeepakSharma04** [zoontek/react-native-permissions#848]
### Before submitting a new issue

- [X] I tested using the latest release of the library, as maybe the bug has been already fixed.
- [X] I checked for possible duplicate issues, with possible answers.

### Bug summary

After updating my react-native project to 0.73.4 and installing this package with latest version ("react-native-permissions": "^4.1.2",) my ios build is failed and showing  Error --->Duplicate case value 'EKAuthorizationStatusDenied'. and.  Use of undeclared identifier 'EKAuthorizationStatusFullAccess'

<img width="1171" alt="Screenshot 2024-02-23 at 4 47 19 PM" src="https://github.com/zoontek/react-native-permissions/assets/96714958/3c10015e-e7d6-41d5-bb0a-78eaa221d99d">

### Library version

4.1.2

### Environment info

```shell
System:
  OS: macOS 12.6.1
  CPU: (8) arm64 Apple M1
  Memory: 365.98 MB / 16.00 GB
  Shell:
    version: 5.8.1
    path: /bin/zsh
Binaries:
  Node:
    version: 18.19.0
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.17
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.2.3
    path: /opt/homebrew/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.14.3
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.2
      - iOS 16.2
      - macOS 13.1
      - tvOS 16.1
      - watchOS 9.1
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11330709
  Xcode:
    version: 14.2/14C18
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.10
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.4
    wanted: 0.73.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Steps to reproduce

After updating my react-native project to 0.73.4 and installing this package with latest version ("react-native-permissions": "^4.1.2",) my ios build is failed and showing  Error --->Duplicate case value 'EKAuthorizationStatusDenied'. and.  Use of undeclared identifier 'EKAuthorizationStatusFullAccess'

### Reproducible sample code

```js
**Pod file setup**

  def node_require(script)
     # Resolve script with node to allow for hoisting
     require Pod::Executable.execute_command('node', ['-p',
      "require.resolve(
        '#{script}',
         {paths: [process.argv[1]]},
      )", __dir__]).strip
   end
  
   node_require('react-native/scripts/react_native_pods.rb')
   node_require('react-native-permissions/scripts/setup.rb')

platform :ios, min_ios_version_supported
prepare_react_native_project!


setup_permissions([
  'AppTrackingTransparency',
  'Bluetooth',
  'Calendars',
  'CalendarsWriteOnly',
  'Camera',
  'Contacts',
  'FaceID',
  'LocationAccuracy',
  'LocationAlways',
  'LocationWhenInUse',
  'MediaLibrary',
  'Microphone',
  'Motion',
  'Notifications',
  'PhotoLibrary',
  'PhotoLibraryAddOnly',
  'Reminders',
  'Siri',
  'SpeechRecognition',
  'StoreKit',
])

flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end


target 'faveo_support_app_master' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )


  # pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'faveo_support_app_masterTests' do
    inherit! :complete
    # Pods for testing
  end

  # # Enables Flipper.
  # #
  # # Note that if you have use_frameworks! enabled, Flipper will not work and
  # # you should disable the next line.
  # use_flipper!()

  # post_install do |installer|
  #   react_native_post_install(installer)
  #   __apply_Xcode_12_5_M1_post_install_workaround(installer)
  # end


  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
    
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end

end
```

**Comment by zoontek** [comment]
Hi @DeepakSharma04, are you using Xcode >=15, like mentioned in [the 4.0.0 release notes](https://github.com/zoontek/react-native-permissions/releases/tag/4.0.0)?

EDIT: You don't

> Xcode:
>   version: 14.2/14C18

**Comment by DeepakSharma04** [comment]
> Hi @DeepakSharma04, are you using Xcode >=15, like mentioned in [the 4.0.0 release notes](https://github.com/zoontek/react-native-permissions/releases/tag/4.0.0)?
> 
> EDIT: You don't
> 
> > Xcode:
> > version: 14.2/14C18

Thanks
