### ISSUE TITLE
Pod install cannot find `install_module_dependencies(s)` method in RNPermissions.podspec 

### ISSUE THREAD

**Issue by boovius** [zoontek/react-native-permissions#824]
### Bug summary

Upgraded recently to v3.10.1 (during an upgrade of ReactNative from 0.68 to 0.70)

Because I'm on ReactNative 0.70 (and not yet on 0.72), I've followed instructions for setup below RN 0.72, adding the line:
```
require_relative '../node_modules/react-native-permissions/scripts/setup'
```
below the following in my Podfile: 
```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
```

Running `pod install` without the flag `RCT_NEW_ARCH_ENABLED` works fine.

However, running `RCT_NEW_ARCH_ENABLED=1 pod install` fails with error: 
```
[!] Invalid `Podfile` file: 
[!] Invalid `RNPermissions.podspec` file: undefined method `install_modules_dependencies' for Pod:Module
Did you mean?  install_flipper_dependencies

 #  from /Users/[redacted]/.../[redacted-root-project-dir]/node_modules/react-native-permissions/RNPermissions.podspec:20
 #  -------------------------------------------
 #    if ENV['RCT_NEW_ARCH_ENABLED'] == "1" then
 >      install_modules_dependencies(s)
 #      s.platforms  = { :ios => "12.4", :tvos => "12.4" }
 #  -------------------------------------------
.

 #  from /Users/[redacted]/.../[redacted-root-project-dir]/ios/Podfile:10
 #  -------------------------------------------
 #  def shared_pods
 >    config = use_native_modules!
 #  
 #  -------------------------------------------
```
(I imagine install_flipper_dependencies must be unique to my environment. Also I'm running a version of cocoapods through Rosetta installed via ruby 2.7.0. Also the minimum ios target for my project is 13.0)

podspec in RNPermissions 3.10.1 has a conditional for the new arch that attempts to run that method but that method seems to be unbound.

No idea what I'm missing or why this is happening. Would GREATLY appreciate any help or insight! 

### Library version

3.10.1

### Environment info

```shell
info Fetching system and libraries information...
System:
    OS: macOS 13.5.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 120.42 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
    Watchman: 2023.09.04.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /Users/boovius/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
  Languages:
    Java: 12.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

----
using a version of cocoapods that seems to still be running through Rosetta installed from  ruby 2.7.0
```

### Steps to reproduce

1. Working on upgrade of react-native from 0.68 to 0.70
2. Update react-native-permissions to latest 3.10.1
3. Run: `RCT_NEW_ARCH_ENABLED=1 pod install`

### Reproducible sample code

```js
RCT_NEW_ARCH_ENABLED=1 pod install

[!] Invalid `Podfile` file: 
[!] Invalid `RNPermissions.podspec` file: undefined method `install_modules_dependencies' for Pod:Module
Did you mean?  install_flipper_dependencies.

 #  from /Users/[redacted]/.../[redacted-root-project-dir]/node_modules/react-native-permissions/RNPermissions.podspec:20
 #  -------------------------------------------
 #    if ENV['RCT_NEW_ARCH_ENABLED'] == "1" then
 >      install_modules_dependencies(s)
 #      s.platforms  = { :ios => "12.4", :tvos => "12.4" }
 #  -------------------------------------------
.

 #  from /Users/[redacted]/.../[redacted-root-project-dir]/ios/Podfile:10
 #  -------------------------------------------
 #  def shared_pods
 >    config = use_native_modules!
 #  
 #  -------------------------------------------
```

**Comment by zoontek** [comment]
New arch is only supported on 0.71+

**Comment by mikehardy** [comment]
find symbol

https://github.com/search?q=repo%3Afacebook%2Freact-native%20install_modules_dependencies&type=code

open file with definition

https://github.com/facebook/react-native/blob/05d92bf2a5ed54c3e7a52b78a3edd699471c710f/packages/react-native/scripts/react_native_pods.rb#L246

switch to blame

https://github.com/facebook/react-native/blame/05d92bf2a5ed54c3e7a52b78a3edd699471c710f/packages/react-native/scripts/react_native_pods.rb#L246

Go  back past the commit that altered it / research for symbol until symbol disappears, that's the commit that introduces it

https://github.com/facebook/react-native/blame/f60b9f695e1c08714735b78366267127b29ab705/packages/react-native/scripts/react_native_pods.rb#L215

this one https://github.com/facebook/react-native/commit/82e9c6ad611f1fb816de056ff031716f8cb24b4e

Earliest release tag on that one is react-native 0.71

That's how to do it when you need to find out

**Comment by boovius** [comment]
Ah amazing thanks for the quick info @zoontek and very extensive teaching @mikehardy 💪 - all very, very helpful!
