### PR TITLE
Fix errors that occur when building for iOS with RN 0.48.0-rc.0.

### PR DESCRIPTION
**Pull request by miyabi**
I noticed that errors occur when building for iOS with RN 0.48.0-rc.0 like below:
```
node_modules/react-native/React/Base/RCTBridgeModule.h:54:16: Redefinition of 'RCTMethodInfo'
node_modules/react-native/React/Base/RCTBridgeModule.h:58:3: Typedef redefinition with different types ('struct (anonymous struct at RCTBridgeModule.h:54:16)' vs 'struct RCTMethodInfo')
```

Because RCTBridgeModule.h is included in RCTBridge.h, I think that RCTBridgeModule.h is not needed to be included separately.

### CODE REVIEW

**Comment by benjdlambert** [comment]
Also effects `v0.47.1` I believe.

**Comment by ayberkanilatsiz** [comment]
@miyabi "react-native": "0.48.1", it's work

**Comment by kesha-antonov** [comment]
@yonahforst please merge to support 0.48

**Comment by grootendorste** [comment]
This works in 0.48.2. There are a bunch of these types of changes, can one of them get merged in?

**Comment by brendan-rius** [comment]
Works for me too
Please merge :)

**Comment by yonahforst** [comment]
closed in favor of #146. @miyabi - thanks for this PR!
